### ISSUE TITLE
As a user, I want to be able to install zsh-users plugins and spaceship-prompt in Oh-My-Zsh

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/dotfiles#8]
## Tasks:
- [ ] Install zsh-syntax-highlighting plugin
- [ ] Install zsh-autocompletion
- [ ] Install spaceship-prompt
